module.exports = {
  jsxSingleQuote: false,
  singleQuote: true,
  printWidth: 100,
  quoteProps: 'as-needed',
  proseWrap: 'preserve',
  arrowParens: 'always',
  trailingComma: 'es5',
  tabWidth: 2,
  semi: false,
  importOrder: [
    '<THIRD_PARTY_MODULES>',
    '^@/services/(.*)$',
    '^@/components/(.*)$',
    '^@/components/blocks/(.*)$',
    '^@/components/partials/(.*)$',
    '^@/components/ui/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  tailwindStylesheet: './src/app/globals.css',
  tailwindFunctions: ['cva', 'cn', 'clsx'],
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
